### ISSUE TITLE
the background view is turn to white

### ISSUE THREAD

**Issue by kaioser** [podkovyrin/DWAlertController#3]
when i present a alert, the background is white , and i did not set the controller's backgrund color

liek this :

 
![test](https://user-images.githubusercontent.com/30762999/87218984-3298cf80-c38a-11ea-9035-1c6d288f85a3.gif)

**Comment by podkovyrin** [comment]
It looks like `modalPresentationStyle` of the alert controller was set to incorrect value (it should be `UIModalPresentationCustom`). Also, notice that the background color of the content controller should be explicitly set to `UIColor.clear`.

**Comment by kaioser** [comment]
> It looks like `modalPresentationStyle` of the alert controller was set to incorrect value (it should be `UIModalPresentationCustom`). Also, notice that the background color of the content controller should be explicitly set to `UIColor.clear`.

here is my code:

<img width="946" alt="test2" src="https://user-images.githubusercontent.com/30762999/87240471-7227f000-c44c-11ea-8eff-c13b2ea20bb0.png">


<img width="1226" alt="test3" src="https://user-images.githubusercontent.com/30762999/87240537-ebbfde00-c44c-11ea-99d1-236e9f1d68ca.png">

Strangely enough, when I was debugging this APP with the cable, it works fine.

but when i did not use the cable, and run this app, the background view is turn to white.

**Comment by podkovyrin** [comment]
The usage of DWAlertController looks good. Btw, you don't need to set `modalPresentationStyle` at all neither on your content controller (`vc`) nor alert itself. All appearance and transitions are managed by DWAlertController class. 
Please check the Example app if you have issues on your device with any of the custom alerts there. I would suggest adding your CMDataSetAlertController to the Example app and check if you still have those background color issues.

**Comment by kaioser** [comment]
> The usage of DWAlertController looks good. Btw, you don't need to set `modalPresentationStyle` at all neither on your content controller (`vc`) nor alert itself. All appearance and transitions are managed by DWAlertController class.
> Please check the Example app if you have issues on your device with any of the custom alerts there. I would suggest adding your CMDataSetAlertController to the Example app and check if you still have those background color issues.

thanks man，I thought again，and i I found there a category in my project, like this:

<img width="566" alt="test4" src="https://user-images.githubusercontent.com/30762999/87245544-be892500-c478-11ea-8b83-6c3de9651c1f.png">

this categoty reload the UIModalPresentationStyle, that's the problem! 

Anyway, thanks man!
